theme: minimal
title: Twain's Tales
about: >

  Hey! I'm Mark Twain, and this is my blog.

footer: > 
  <small>Theme by orderedlist. Ported by [Mihir Singh](http://mihir.xxx) ([@citruspi](http://github.com/citruspi)).
  <br/>
  Powered by [ford.py](http://github.com/citruspi/ford.py)</small>

post_blog: >

  ## About Me


  Samuel Langhorne Clemens (November 30, 1835 – April 21, 1910), better known by his pen name Mark Twain, was an American author and humorist. He is most noted for his novel The Adventures of Tom Sawyer (1876) and its sequel, Adventures of Huckleberry Finn (1885), the latter often called "the Great American Novel."


  He achieved great success as a writer and public speaker. His wit and satire earned praise from critics and peers, and he was a friend to presidents, artists, industrialists, and European royalty.
  

  ([via Wikipedia.org](http://en.wikipedia.org/wiki/Mark_Twain)).